### ISSUE TITLE
MissingFieldException: Field 'Planetbase.GameManager.mCurrentFrameCount' not found

### ISSUE THREAD

**Issue by mnarax** [PiMaker/PlanetbasePatcher#1]
I used that patch on v1.2.2 and I got that exception (after the start the game not from the patcher). Any idea?

**Comment by PiMaker** [comment]
I'm no longer maintaining this project, but you can try https://github.com/winsock/PlanetbasePatcher ... Although I'm not positive about the state of that one too. Good luck :)
